# Generated by Django 4.2 on 2023-08-21 07:37

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='slider/img')),
                ('main_title', models.CharField(max_length=2000)),
                ('experience', models.CharField(max_length=3)),
                ('title', models.CharField(max_length=255)),
                ('sub_title', models.CharField(max_length=255)),
                ('how_to_work', models.CharField(max_length=255)),
                ('mission', models.CharField(max_length=2000)),
                ('vision', models.CharField(max_length=2000)),
                ('values', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Back_Graound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, null=True)),
                ('fqa', models.ImageField(upload_to='BackGraound')),
                ('blog', models.ImageField(upload_to='BackGraound')),
                ('blog_details', models.ImageField(upload_to='BackGraound')),
                ('wishlist', models.ImageField(upload_to='BackGraound')),
                ('doctor', models.ImageField(upload_to='BackGraound')),
                ('doctor_details', models.ImageField(upload_to='BackGraound')),
                ('service', models.ImageField(upload_to='BackGraound')),
                ('service_details', models.ImageField(upload_to='BackGraound')),
                ('media', models.ImageField(upload_to='BackGraound')),
                ('contact', models.ImageField(upload_to='BackGraound')),
            ],
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='banner/img')),
                ('name', models.CharField(max_length=250, null=True)),
                ('line_1', models.CharField(max_length=250, null=True)),
                ('line_2', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Companylogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='slider/img')),
                ('name', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('where_we_are', models.CharField(max_length=2000)),
                ('form_name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('number', models.CharField(max_length=255)),
                ('email_id', models.EmailField(max_length=255)),
                ('location_map', models.CharField(blank=True, max_length=2500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Content_Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('primary', 'primary'), ('secondary', 'secondary'), ('success', 'success'), ('danger', 'danger'), ('warning', 'warning'), ('info', 'info'), ('dark', 'dark'), ('body', 'body'), ('white', 'white'), ('transparent', 'transparent'), ('light', 'light')], max_length=100)),
                ('contant_1', models.CharField(max_length=250, null=True)),
                ('contant_2', models.CharField(max_length=250, null=True)),
                ('contant_3', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='slider/img')),
                ('name', models.CharField(max_length=250, null=True)),
                ('event', models.CharField(choices=[('UPCOMING', 'UPCOMING'), ('COMPLETATE', 'COMPLETATE')], max_length=20)),
                ('description', models.CharField(max_length=500, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=250, null=True)),
                ('answers', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Featured',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='service/featured')),
                ('name', models.CharField(max_length=250, null=True)),
                ('title', models.CharField(max_length=250, null=True)),
                ('description', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('primary', 'primary'), ('secondary', 'secondary'), ('success', 'success'), ('danger', 'danger'), ('warning', 'warning'), ('info', 'info'), ('dark', 'dark'), ('body', 'body'), ('white', 'white'), ('transparent', 'transparent'), ('light', 'light')], max_length=100)),
                ('facebook', models.CharField(max_length=250, null=True)),
                ('youtube', models.CharField(max_length=250, null=True)),
                ('whatsApp', models.CharField(max_length=250, null=True)),
                ('instagram', models.CharField(max_length=250, null=True)),
                ('telegram', models.CharField(max_length=250, null=True)),
                ('pinterest', models.CharField(max_length=250, null=True)),
                ('twitter', models.CharField(max_length=250, null=True)),
                ('linkedIn', models.CharField(max_length=250, null=True)),
                ('copyright', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='slider/img')),
                ('color', models.CharField(choices=[('primary', 'primary'), ('secondary', 'secondary'), ('success', 'success'), ('danger', 'danger'), ('warning', 'warning'), ('info', 'info'), ('dark', 'dark'), ('body', 'body'), ('white', 'white'), ('transparent', 'transparent'), ('light', 'light')], max_length=100)),
                ('number', models.CharField(max_length=12, null=True)),
                ('contant_1', models.CharField(max_length=250, null=True)),
                ('contant_2', models.CharField(max_length=250, null=True)),
                ('contant_3', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favicon', models.ImageField(upload_to='favicon')),
                ('title', models.CharField(max_length=500, null=True)),
                ('keyword', models.CharField(max_length=500, null=True)),
                ('discriptaion', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=250, null=True)),
                ('hindi_name', models.CharField(max_length=250, null=True)),
                ('sort_description', models.CharField(max_length=250, null=True)),
                ('future_image', models.ImageField(upload_to='service/img')),
                ('description', ckeditor.fields.RichTextField()),
                ('slug', models.SlugField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'app_Service',
            },
        ),
        migrations.CreateModel(
            name='Service_Categoray',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='slider/img')),
                ('name', models.CharField(max_length=250, null=True)),
                ('name_hindi', models.CharField(max_length=250, null=True)),
                ('description', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='slider/img')),
                ('line_1', models.CharField(max_length=250, null=True)),
                ('line_2', models.CharField(max_length=250, null=True)),
                ('line_3', models.CharField(max_length=250, null=True)),
                ('line_4', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='service/social')),
                ('name', models.CharField(max_length=250, null=True)),
                ('link', models.CharField(max_length=550, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='service/team')),
                ('name', models.CharField(max_length=250, null=True)),
                ('title', models.CharField(max_length=250, null=True)),
                ('description', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='service/tpa')),
                ('company', models.CharField(max_length=250, null=True)),
                ('description', models.CharField(max_length=250, null=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.service')),
            ],
        ),
        migrations.CreateModel(
            name='Service_Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=250, null=True)),
                ('answers', models.CharField(max_length=500, null=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.service')),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='categoray',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.service_categoray'),
        ),
    ]
