# Generated by Django 4.2 on 2023-08-21 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companylogo',
            name='web_link',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
