# Generated by Django 4.2 on 2023-08-21 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0001_initial'),
        ('app', '0002_companylogo_web_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='industry',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='utility.category'),
            preserve_default=False,
        ),
    ]
