# Generated by Django 4.2.3 on 2023-07-29 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0001_initial'),
        ('business', '0003_alter_business_info_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business_info',
            name='slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='response',
            name='intested_for',
            field=models.ManyToManyField(blank=True, null=True, to='utility.intested_for'),
        ),
    ]
